GastoEnergetico/Controllers/CategoriasController.cs
using GastoEnergetico.Models.Categorias;
using GastoEnergetico.RequestModels.Categorias;
using GastoEnergetico.ViewModels.Categorias;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static GastoEnergetico.ViewModels.Categorias.IndexViewModel;

namespace GastoEnergetico.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly CategoriasService _categoriasService;

        public CategoriasController(CategoriasService categoriasService)
        {
            _categoriasService = categoriasService;
        }

        // GET
        public IActionResult Index()
        {
            //View para exibição de dados para o usuário
            var viewModel = new IndexViewModel();


            //Busca todos os gastos
            var listaCategoriasEntities = _categoriasService.BuscarTodos();

            //Processar a lista e passar para ViewModel
            foreach (CategoriasEntity categoriasEntity in listaCategoriasEntities)
            {
                viewModel.Categorias.Add(new Categoria()
                {
                    Id = categoriasEntity.Id.ToString(),
                    Descricao = categoriasEntity.Descricao,
                    CategoriaPaiId = categoriasEntity.CategoriaPaiId.ToString()
                });

            }

            return View(viewModel);
        }


        [HttpGet]
        public IActionResult Adicionar()
        {
            var viewModel = new AdicionarViewModel();


            viewModel.ValidarEFiltrar();

            return View();
        }

        [HttpPost]
        public RedirectToActionResult Adicionar(AdicionarRequestModel requestModel)
        {
            try
            {
                _categoriasService.Adicionar(requestModel);
                TempData["FormMensSucess"] = "Categorias adiconadas com sucesso.";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return RedirectToAction("Adicionar");
            }

        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            try
            {
                var entidadeEsc = _categoriasService.ObterPorId(id);

                var viewModel = new EditarViewModel()
                {
                    Id = entidadeEsc.Id.ToString(),
                    Descricao = entidadeEsc.Descricao,
                    CategoriaPaiId = entidadeEsc.CategoriaPaiId.ToString()
                };

                return View(viewModel);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(int id, EditarRequestModel requestModel)
        {
            try
            {
                _categoriasService.Editar(id, requestModel);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return RedirectToAction("Editar");
            }
        }

        [HttpGet]
        public IActionResult Remover(int id)
        {
            try
            {
                var entidadeEsc = _categoriasService.ObterPorId(id);
                var viewModel = new RemoverViewModel()
                {
                    Id = entidadeEsc.Id.ToString(),
                    Descricao = entidadeEsc.Descricao,
                    CategoriaPaiId = entidadeEsc.CategoriaPaiId.ToString()
                };

                return View(viewModel);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public RedirectToActionResult Remover(int id, object requestModel)
        {
            try
            {
                _categoriasService.Remover(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return RedirectToAction("Remover");
            }
        }
    }
}

GastoEnergetico/Controllers/ItensController.cs
using GastoEnergetico.Models.Categorias;
using GastoEnergetico.Models.Itens;
using GastoEnergetico.ViewModels.Itens;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static GastoEnergetico.ViewModels.Itens.IndexViewModel;

namespace GastoEnergetico.Controllers
{
    public class ItensController : Controller
    {
        private readonly ItensService _itensService;
        private readonly CategoriasService _categoriasService;


        public ItensController(ItensService itensService, CategoriasService categoriasService)
        {
            _itensService = itensService;
            _categoriasService = categoriasService;
        }

        public IActionResult Index()
        {

            var viewModel = new IndexViewModel();

            //Busca todos os gastos
            var listaItensEntities = _itensService.BuscarTodos();

            //Processar a lista e passar para ViewModel
            foreach (ItensEntity itensEntity in listaItensEntities)
            {
                viewModel.Items.Add(new Item
                {
                    Id = itensEntity.Id.ToString(),
                    Categoria = itensEntity.Categoria.Id.ToString(),
                    Nome = itensEntity.Nome,
                    Descricao = itensEntity.Descricao,
                    DataFabricacao = itensEntity.DataFabricacao.ToShortDateString(),
                    ConsumoWatts = itensEntity.ConsumoWatts.ToString("N"),
                    HorasUsoDiario = itensEntity.HorasUsoDiario.ToString()

                });

            }

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Adicionar()
        {
            var viewModel = new AdicionarViewModel();


            viewModel.ValidarEFiltrar();

            return View();
        }
    }
}

GastoEnergetico/Controllers/ParametrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GastoEnergetico.Models.Parametros;
using GastoEnergetico.RequestModels.Parametros;
using GastoEnergetico.ViewModels.Parametros;
using Microsoft.AspNetCore.Mvc;
using static GastoEnergetico.ViewModels.Parametros.IndexViewModel;

namespace GastoEnergetico.Controllers
{
    public class ParametrosController : Controller
    {

        private readonly ParametrosService _parametrosService;


        public ParametrosController(ParametrosService parametrosService)
        {
            _parametrosService = parametrosService;
        }

        public IActionResult Index()
        {
            //View para exibição de dados para o usuário
            var viewModel = new IndexViewModel();

            //Busca todos os gastos
            var listaParametrosEntities = _parametrosService.BuscarTodos();

            //Processar a lista e passar para ViewModel
            foreach (ParametrosEntity parametrosEntity in listaParametrosEntities)
            {
                viewModel.Parametros.Add(new Parametro()
                {
                    Id = parametrosEntity.Id.ToString(),
                    FaixaConsumoAlto = parametrosEntity.FaixaConsumoAlto.ToString("N"),
                    FaixaConsumoMedio = parametrosEntity.FaixaConsumoMedio.ToString("N"),
                    ValorKwh = parametrosEntity.ValorKwh.ToString("C")
                });
            }

            return View(viewModel);
        }


        [HttpGet]
        public IActionResult Adicionar()
        {
            var viewModel = new AdicionarViewModel();


            viewModel.ValidarEFiltrar();

            return View();
        }

        [HttpPost]
        public RedirectToActionResult Adicionar(AdicionarRequestModel requestModel)
        {
            try
            {
                _parametrosService.Adicionar(requestModel);
                TempData["FormMensSucess"] = "Parâmetros adiconados com sucesso.";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return RedirectToAction("Adicionar");
            }

        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            try
            {
                var entidadeEsc = _parametrosService.ObterPorId(id);

                var viewModel = new EditarViewModel()
                {
                    Id = entidadeEsc.Id.ToString(),
                    ValorKwh = entidadeEsc.ValorKwh.ToString("C"),
                    FaixaConsumoAlto = entidadeEsc.FaixaConsumoAlto.ToString("N"),
                    FaixaConsumoMedio = entidadeEsc.FaixaConsumoMedio.ToString("N")
                };

                return View(viewModel);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(int id, EditarRequestModel requestModel)
        {
            try
            {
                _parametrosService.Editar(id, requestModel);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return RedirectToAction("Editar");
            }
        }

    }
}

GastoEnergetico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gasto Energetico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gasto Energetico</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Itens" asp-action="Index">Itens</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parametros" asp-action="Index">Parâmetros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GastoEnergetico - Todos os direitos reservados
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>